[project]
name = "rifffriends"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.4",
    "pre-commit>=4.0.1",
    "ruff>=0.8.4",
    "toml>=0.10.2",
]
